---
permalink: events/task_upload_new_active_iq_rules_file.html 
sidebar: sidebar 
keywords: upload, new, active iq, rules, file 
summary: Unified Manager は、新しい Active IQ ルールファイルの有無を自動的にチェックし、ある場合は新しいファイルをダウンロードします。ただし、外部ネットワークへのアクセスがないサイトでは、ルールファイルを手動でアップロードする必要があります。 
---
= 新しい Active IQ ルールファイルをアップロードしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager は、新しい Active IQ ルールファイルの有無を自動的にチェックし、ある場合は新しいファイルをダウンロードします。ただし、外部ネットワークへのアクセスがないサイトでは、ルールファイルを手動でアップロードする必要があります。

* 必要なもの *

* Active IQ イベントレポートを有効にしておく必要があります。
* ルールファイルをネットアップサポートサイトからダウンロードする必要があります。


ストレージシステムを確実に保護し、最適な状態で運用を続けるために、月に一度は新しいルールファイルをダウンロードすることを推奨します。ルールファイルは次の場所にあります。 http://mysupport.netapp.com/NOW/public/unified_manager/bin/secure_rules.zip[]

.手順
. ネットワークにアクセスできるコンピュータで、ネットアップサポートサイトにアクセスし、最新のルール「 .zip 」ファイルをダウンロードします。
. ルールファイルをセキュリティエリアに持ち出すことができるメディアに転送し、セキュリティエリアのシステムにコピーします。
. 左側のナビゲーションペインで、 * Storage Management * > * Event Setup * をクリックします。
. [ * イベントの設定 * ] ページで、 [ * ルールのアップロード * ] ボタンをクリックします。
. [ * ルールのアップロード * ] ダイアログボックスで、ダウンロードしたルール「 .zip 」ファイルに移動して選択し、 [ * アップロード * ] をクリックします。
+
この処理には数分かかることがあります。



ルールファイルが Unified Manager サーバに解凍されます。午前 0 時過ぎに管理対象クラスタで AutoSupport ファイルが生成されたあと、 Unified Manager がルールファイルに照らしてクラスタをチェックし、必要に応じて新しいリスクイベントとインシデントイベントを生成します。

詳細については、次の技術情報アーティクル（KB）を参照してください。 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/How_to_update_AIQCASecure_rules_manually_in_AIQUM["AIQUMでAIQCASecureルールを手動で更新する方法"]
